// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lekcsmzjsfojomkmqqsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxla2NzbXpqc2Zvam9ta21xcXNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTQ3MzIsImV4cCI6MjA2NTczMDczMn0.tUHKbSfhadty3W0QiEAFDxIVrC_XmAoUExxYLWN6WI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);